apiVersion: v1
data:
  password: ZHJnbWdyZGJhMDE=
  username: ZHJnbWdyZGJhMDE=
kind: Secret
metadata:
  creationTimestamp: '2022-05-30T15:30:32Z'
  name: db-credentials
  namespace: dev
  resourceVersion: '32335'
  selfLink: /api/v1/namespaces/dev/secrets/db-credentials
  uid: 71cc845e-e02d-11ec-870a-0800277e68cc
type: Opaque